{% set name = "cppad" %}
{% set version = "20230000.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/coin-or/CppAD/archive/{{ version }}.tar.gz
  sha256: 339018f18effe35e1d9845bb7c7070e726396f37244b1855fb242c8b89d0b623

build:
  number: 0
  # No ABI policy documented, let's be conservative 
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [linux]

test:
  commands:
    - test -d ${PREFIX}/include/cppad  # [unix]
    - test -f ${PREFIX}/share/pkgconfig/cppad.pc  # [unix]
    - test -f ${PREFIX}/lib/libcppad_lib.so  # [linux]
    - test -f ${PREFIX}/lib/libcppad_lib.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\include\\cppad exit 1  # [win]
    - if not exist %PREFIX%\\Library\\share\\pkgconfig\\cppad.pc exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cppad_lib.lib exit 1  # [win]

about:
  home: https://coin-or.github.io/CppAD
  license: EPL-2.0
  license_file: epl-2.0.txt
  summary: CppAD - A Package for Differentiation of C++ Algorithms

  dev_url: https://github.com/coin-or/CppAD
  doc_url: https://coin-or.github.io/CppAD/doc/cppad.htm

extra:
  recipe-maintainers:
    - traversaro
    - jcarpent
